version: '3.8'

services:
  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db-data:/var/lib/mysql

  app:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://symfony:symfony@db:3306/app?serverVersion=mariadb-10.5"
    volumes:
      - .:/var/www/html

volumes:
  db-data:
